In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('month_total_sales.csv')
df

                     month  total_sales
0   2023-01-01 00:00:00+09      17496.0
1   2023-02-01 00:00:00+09       7915.0
2   2023-03-01 00:00:00+09      50627.0
3   2023-04-01 00:00:00+09      24575.0
4   2023-05-01 00:00:00+09      22793.0
5   2023-06-01 00:00:00+09      28746.0
6   2023-07-01 00:00:00+09      34931.0
7   2023-08-01 00:00:00+09      24665.0
8   2023-09-01 00:00:00+09      71960.0
9   2023-10-01 00:00:00+09      27923.0
10  2023-11-01 00:00:00+09      70610.0
11  2023-12-01 00:00:00+09      62795.0
12  2024-01-01 00:00:00+09      20054.0
13  2024-02-01 00:00:00+09      11134.0
14  2024-03-01 00:00:00+09      36362.0
15  2024-04-01 00:00:00+09      32488.0
16  2024-05-01 00:00:00+09      23023.0
17  2024-06-01 00:00:00+09      24047.0
18  2024-07-01 00:00:00+09      26119.0
19  2024-08-01 00:00:00+09      28487.0
20  2024-09-01 00:00:00+09      54529.0
21  2024-10-01 00:00:00+09      26804.0
22  2024-11-01 00:00:00+09      71110.0
23  2024-12-01 00:00:00+09      61630.0
24  2025-01-01 00:00:00+09      18799.0
25  2025-02-01 00:00:00+09      29878.0
26  2025-03-01 00:00:00+09      49766.0
27  2025-04-01 00:00:00+09      38889.0
28  2025-05-01 00:00:00+09      48663.0
29  2025-06-01 00:00:00+09      40803.0
30  2025-07-01 00:00:00+09      36511.0
31  2025-08-01 00:00:00+09      23839.0
32  2025-09-01 00:00:00+09      61291.0
33  2025-10-01 00:00:00+09      39185.0
34  2025-11-01 00:00:00+09      68989.0
35  2025-12-01 00:00:00+09      78544.0
36  2026-01-01 00:00:00+09      44270.0
37  2026-02-01 00:00:00+09      31694.0
38  2026-03-01 00:00:00+09      44086.0
39  2026-04-01 00:00:00+09      33733.0
40  2026-05-01 00:00:00+09      45484.0
41  2026-06-01 00:00:00+09      42952.0
42  2026-07-01 00:00:00+09      43538.0
43  2026-08-01 00:00:00+09      46843.0
44  2026-09-01 00:00:00+09      74643.0
45  2026-10-01 00:00:00+09      67197.0
46  2026-11-01 00:00:00+09      87908.0
47  2026-12-01 00:00:00+09      65530.0

In [22]:
df['month'] = pd.to_datetime(df['month'])

In [23]:
df['year'] = df['month'].dt.year
df['month_num'] = df['month'].dt.month

In [24]:
X = df[['year', 'month_num']]
y = df['total_sales']

In [25]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

model.fit(X,y)

RandomForestRegressor(n_estimators=200, random_state=42)

In [26]:
future = pd.DataFrame({
    "year": [2025, 2025, 2025],
    "month_num": [1, 2, 3]
})

In [27]:
future["predicted_sales"] = model.predict(future)
future

   year  month_num  predicted_sales
0  2025          1         25540.64
1  2025          2         26610.72
2  2025          3         46598.21

In [28]:
future.to_csv(
    "sales_forecast.csv",
    index=False
)