In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("stock_market_clean.csv")

In [3]:
# Select Apple stock
aapl = df[df["Ticker"] == "AAPL"].copy()

# Sort chronologically
aapl = aapl.sort_values("Date").reset_index(drop=True)

# Create the prediction target
aapl["Target"] = aapl["Close"].shift(-1)

print(aapl[["Date", "Close", "Target"]].head(10))

         Date       Close      Target
0  2021-10-11  142.809998  141.509995
1  2021-10-12  141.509995  140.910004
2  2021-10-13  140.910004  143.759995
3  2021-10-14  143.759995  144.839996
4  2021-10-15  144.839996  146.550003
5  2021-10-18  146.550003  148.759995
6  2021-10-19  148.759995  149.259995
7  2021-10-20  149.259995  149.479996
8  2021-10-21  149.479996  148.690002
9  2021-10-22  148.690002  148.639999

daily return

In [4]:
aapl

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker,Target
0,2021-10-11,142.270004,144.809998,141.809998,142.809998,139.292725,64452200,AAPL,141.509995
1,2021-10-12,143.229996,143.250000,141.039993,141.509995,138.024750,73035900,AAPL,140.910004
2,2021-10-13,141.240005,141.399994,139.199997,140.910004,137.439560,78762700,AAPL,143.759995
3,2021-10-14,142.110001,143.880005,141.509995,143.759995,140.219345,69907100,AAPL,144.839996
4,2021-10-15,143.770004,144.899994,143.509995,144.839996,141.272751,67940300,AAPL,146.550003
...,...,...,...,...,...,...,...,...,...
1250,2026-10-05,332.820007,336.209991,331.649994,332.890015,332.890015,34400900,AAPL,333.630005
1251,2026-10-06,332.279999,334.380005,330.619995,333.630005,333.630005,30449000,AAPL,336.670013
1252,2026-10-07,336.959991,338.670013,332.779999,336.670013,336.670013,34147900,AAPL,340.420013
1253,2026-10-08,336.820007,341.570007,335.899994,340.420013,340.420013,35332400,AAPL,336.640015
1254,2026-10-09,331.700012,338.609985,330.700012,336.640015,336.640015,37855000,AAPL,NaN

Daily Return

In [5]:
aapl["Daily_Return"] = aapl["Close"].pct_change()

MA7

In [6]:
aapl["MA7"] = aapl["Close"].rolling(7).mean()

MA30

In [7]:
aapl["MA30"] = aapl["Close"].rolling(30).mean()

In [8]:
aapl

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker,Target,Daily_Return,MA7,MA30
0,2021-10-11,142.270004,144.809998,141.809998,142.809998,139.292725,64452200,AAPL,141.509995,NaN,NaN,NaN
1,2021-10-12,143.229996,143.250000,141.039993,141.509995,138.024750,73035900,AAPL,140.910004,-0.009103,NaN,NaN
2,2021-10-13,141.240005,141.399994,139.199997,140.910004,137.439560,78762700,AAPL,143.759995,-0.004240,NaN,NaN
3,2021-10-14,142.110001,143.880005,141.509995,143.759995,140.219345,69907100,AAPL,144.839996,0.020226,NaN,NaN
4,2021-10-15,143.770004,144.899994,143.509995,144.839996,141.272751,67940300,AAPL,146.550003,0.007513,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1250,2026-10-05,332.820007,336.209991,331.649994,332.890015,332.890015,34400900,AAPL,333.630005,-0.002397,334.112858,327.797000
1251,2026-10-06,332.279999,334.380005,330.619995,333.630005,333.630005,30449000,AAPL,336.670013,0.002223,333.050001,328.573334
1252,2026-10-07,336.959991,338.670013,332.779999,336.670013,336.670013,34147900,AAPL,340.420013,0.009112,332.802861,329.465668
1253,2026-10-08,336.820007,341.570007,335.899994,340.420013,340.420013,35332400,AAPL,336.640015,0.011139,334.377149,330.364668
1254,2026-10-09,331.700012,338.609985,330.700012,336.640015,336.640015,37855000,AAPL,NaN,-0.011104,334.894296,331.100002