import libraries

In [42]:
import yfinance as yf
import pandas as pd
import numpy as np

download data

In [43]:
ticker = ["AAPL", "NVDA", "AMZN", "TSLA", "JPM"]

all_ticker_data = []

for ticker_symbol in ticker:

    ticker_data = yf.download(
        ticker_symbol,
        period="5y",
        auto_adjust=False
    )

    ticker_data.columns = ticker_data.columns.get_level_values(0)

    ticker_data = ticker_data.reset_index()

    ticker_data["Ticker"] = ticker_symbol

    all_ticker_data.append(ticker_data)

df = pd.concat(all_ticker_data, ignore_index=True)

df

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Price,Date,Adj Close,Close,High,Low,Open,Volume,Ticker
0,2021-08-23,146.022812,149.710007,150.190002,147.889999,148.309998,60131800,AAPL
1,2021-08-24,145.935013,149.619995,150.860001,149.149994,149.449997,48606400,AAPL
2,2021-08-25,144.706039,148.360001,150.320007,147.800003,149.809998,58991300,AAPL
3,2021-08-26,143.906250,147.539993,149.119995,147.509995,148.350006,48597200,AAPL
4,2021-08-27,144.940140,148.600006,148.750000,146.830002,147.479996,55802400,AAPL
...,...,...,...,...,...,...,...,...
6270,2026-08-17,360.959991,360.959991,365.750000,360.959991,361.940002,5282600,JPM
6271,2026-08-18,363.250000,363.250000,363.570007,359.269989,362.339996,5525100,JPM
6272,2026-08-19,357.260010,357.260010,363.049988,355.649994,363.010010,6696200,JPM
6273,2026-08-20,351.549988,351.549988,357.950012,351.549988,357.600006,6799700,JPM
6274,2026-08-21,351.579987,351.579987,356.859985,350.369995,354.070007,8073400,JPM

In [44]:
df.head()

Price,Date,Adj Close,Close,High,Low,Open,Volume,Ticker
0,2021-08-23,146.022812,149.710007,150.190002,147.889999,148.309998,60131800,AAPL
1,2021-08-24,145.935013,149.619995,150.860001,149.149994,149.449997,48606400,AAPL
2,2021-08-25,144.706039,148.360001,150.320007,147.800003,149.809998,58991300,AAPL
3,2021-08-26,143.906250,147.539993,149.119995,147.509995,148.350006,48597200,AAPL
4,2021-08-27,144.940140,148.600006,148.750000,146.830002,147.479996,55802400,AAPL

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6275 entries, 0 to 6274
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       6275 non-null   datetime64[ns]
 1   Adj Close  6275 non-null   float64
 2   Close      6275 non-null   float64
 3   High       6275 non-null   float64
 4   Low        6275 non-null   float64
 5   Open       6275 non-null   float64
 6   Volume     6275 non-null   int64
 7   Ticker     6275 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(1), object(1)
memory usage: 392.3+ KB

In [46]:
df.describe()

Price,Date,Adj Close,Close,High,Low,Open,Volume
count,6275,6275.000000,6275.000000,6275.000000,6275.000000,6275.000000,6.275000e+03
mean,2024-02-20 03:29:58.565737216,188.551326,190.767236,193.521094,187.889558,190.738124,1.190736e+08
min,2021-08-23 00:00:00,11.199243,11.227000,11.735000,10.813000,10.971000,3.220500e+06
25%,2022-11-17 00:00:00,132.653496,138.019997,139.674995,136.025002,138.084999,3.517235e+07
50%,2024-02-21 00:00:00,181.050003,182.410004,184.699997,179.910004,182.399994,6.163880e+07
75%,2025-05-22 00:00:00,238.897156,241.540001,245.264999,237.729996,241.799995,1.225152e+08
max,2026-08-21 00:00:00,489.880005,489.880005,498.829987,485.329987,489.880005,1.543911e+09
std,NaN,91.686067,91.255210,92.880822,89.629251,91.300665,1.564819e+08

In [47]:
df.shape

(6275, 8)

In [48]:
df.columns

Index(['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume',
       'Ticker'],
      dtype='object', name='Price')

Question 1 — Overall performance

In [49]:
df1 = df[["Date", "Ticker", "Adj Close"]]
df1.columns = ['date', 'ticker', 'price']
df1

           date ticker       price
0    2021-08-23   AAPL  146.022812
1    2021-08-24   AAPL  145.935013
2    2021-08-25   AAPL  144.706039
3    2021-08-26   AAPL  143.906250
4    2021-08-27   AAPL  144.940140
...         ...    ...         ...
6270 2026-08-17    JPM  360.959991
6271 2026-08-18    JPM  363.250000
6272 2026-08-19    JPM  357.260010
6273 2026-08-20    JPM  351.549988
6274 2026-08-21    JPM  351.579987

[6275 rows x 3 columns]

In [50]:
df1 = df1.pivot_table(index=['date'], columns='ticker', values=['price'])
df1.columns = [col[1] for col in df1.columns.values]
df1

                  AAPL        AMZN         JPM        NVDA        TSLA
date
2021-08-23  146.022812  163.293503  138.273087   21.882311  235.433334
2021-08-24  145.935013  165.289001  139.128998   21.717880  236.163330
2021-08-25  144.706039  164.959000  141.996841   22.136431  237.066666
2021-08-26  143.906250  165.800003  142.729233   21.991932  233.720001
2021-08-27  144.940140  167.481506  143.876358   22.557974  237.306671
...                ...         ...         ...         ...         ...
2026-08-17  305.589996  261.309998  360.959991  225.009995  339.299988
2026-08-18  310.029999  259.450012  363.250000  219.740005  336.869995
2026-08-19  316.829987  265.839996  357.260010  217.559998  351.119995
2026-08-20  311.299988  260.109985  351.549988  216.850006  345.130005
2026-08-21  309.350006  258.630005  351.579987  214.720001  362.859985

[1255 rows x 5 columns]

In [51]:
overall_performance = (df1.iloc[-1] - df1.iloc[0]) / df1.iloc[0]
overall_performance * 100

AAPL    111.850465
AMZN     58.383524
JPM     154.264944
NVDA    881.249204
TSLA     54.124303
dtype: float64

Question 2 — Daily returnsDaily returns

In [52]:
daily_return = df1.pct_change().dropna()
daily_return

                AAPL      AMZN       JPM      NVDA      TSLA
date
2021-08-24 -0.000601  0.012220  0.006190 -0.007514  0.003101
2021-08-25 -0.008421 -0.001997  0.020613  0.019272  0.003825
2021-08-26 -0.005527  0.005098  0.005158 -0.006528 -0.014117
2021-08-27  0.007184  0.010142  0.008037  0.025739  0.015346
2021-08-30  0.030417  0.021477 -0.016007  0.002297  0.026674
...              ...       ...       ...       ...       ...
2026-08-17 -0.001111 -0.005102 -0.005181 -0.000666 -0.008677
2026-08-18  0.014529 -0.007118  0.006344 -0.023421 -0.007162
2026-08-19  0.021933  0.024629 -0.016490 -0.009921  0.042301
2026-08-20 -0.017454 -0.021554 -0.015983 -0.003263 -0.017060
2026-08-21 -0.006264 -0.005690  0.000085 -0.009822  0.051372

[1254 rows x 5 columns]