import libraries

In [6]:
import yfinance as yf
import pandas as pd
import numpy as np

download data

In [11]:
ticker = ["AAPL", "NVDA", "AMZN", "TSLA", "JPM"]

all_ticker_data = []

for ticker_symbol in ticker:

    ticker_data = yf.download(
        ticker_symbol,
        period="5y"
    )

    ticker_data.columns = ticker_data.columns.get_level_values(0)

    ticker_data = ticker_data.reset_index()

    ticker_data["Ticker"] = ticker_symbol

    all_ticker_data.append(ticker_data)

df = pd.concat(all_ticker_data, ignore_index=True)

df

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Price,Date,Close,High,Low,Open,Volume,Ticker
0,2021-08-23,146.022812,146.490986,144.247629,144.657283,60131800,AAPL
1,2021-08-24,145.935043,147.144509,145.476618,145.769232,48606400,AAPL
2,2021-08-25,144.706070,146.617804,144.159864,146.120355,58991300,AAPL
3,2021-08-26,143.906250,145.447338,143.876990,144.696313,48597200,AAPL
4,2021-08-27,144.940155,145.086455,143.213744,143.847729,55802400,AAPL
...,...,...,...,...,...,...,...
6270,2026-08-17,360.959991,365.750000,360.959991,361.940002,5282600,JPM
6271,2026-08-18,363.250000,363.570007,359.269989,362.339996,5525100,JPM
6272,2026-08-19,357.260010,363.049988,355.649994,363.010010,6696200,JPM
6273,2026-08-20,351.549988,357.950012,351.549988,357.600006,6799700,JPM
6274,2026-08-21,351.579987,356.859985,350.366608,354.070007,5579895,JPM

In [8]:
df.head()

Price,Date,Close,High,Low,Open,Volume,Ticker
0,2026-03-23,251.042007,254.146468,249.834156,253.517585,40546100,AAPL
1,2026-03-24,251.191727,254.376046,249.105453,249.904031,45152300,AAPL
2,2026-03-25,252.169983,254.545748,251.151811,253.647357,28476700,AAPL
3,2026-03-26,252.439514,256.542193,250.323295,251.670882,41796700,AAPL
4,2026-03-27,248.356796,255.034881,247.628101,253.447702,47900000,AAPL

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 530 entries, 0 to 529
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    530 non-null    datetime64[ns]
 1   Close   530 non-null    float64
 2   High    530 non-null    float64
 3   Low     530 non-null    float64
 4   Open    530 non-null    float64
 5   Volume  530 non-null    int64
 6   Ticker  530 non-null    object
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 29.1+ KB

In [10]:
df.describe()

Price,Date,Close,High,Low,Open,Volume
count,530,530.000000,530.000000,530.000000,530.000000,5.300000e+02
mean,2026-06-06 20:36:13.584905472,290.125340,294.089498,286.035212,289.962164,6.125409e+07
min,2026-03-23 00:00:00,164.977722,169.252739,164.078776,166.775632,4.366800e+06
25%,2026-04-29 00:00:00,238.349998,242.209999,234.969994,237.569996,3.089715e+07
50%,2026-06-06 12:00:00,294.085693,296.793407,290.749510,293.217120,4.492865e+07
75%,2026-07-16 00:00:00,332.930000,336.461293,328.610133,333.118243,7.476485e+07
max,2026-08-21 00:00:00,445.269989,453.399994,441.160004,446.489990,2.894106e+08
std,NaN,65.346781,66.574353,63.985796,65.251347,5.216259e+07

In [12]:
df.shape

(6275, 7)

In [13]:
df.columns

Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker'], dtype='object', name='Price')

Question 1 — Overall performance

In [19]:
df["Return"] = (
    df.groupby("Ticker")["Volume"]
    .pct_change()
)
df

Price,Date,Close,High,Low,Open,Volume,Ticker,Return
0,2021-08-23,146.022812,146.490986,144.247629,144.657283,60131800,AAPL,NaN
1,2021-08-24,145.935043,147.144509,145.476618,145.769232,48606400,AAPL,-0.191669
2,2021-08-25,144.706070,146.617804,144.159864,146.120355,58991300,AAPL,0.213653
3,2021-08-26,143.906250,145.447338,143.876990,144.696313,48597200,AAPL,-0.176197
4,2021-08-27,144.940155,145.086455,143.213744,143.847729,55802400,AAPL,0.148264
...,...,...,...,...,...,...,...,...
6270,2026-08-17,360.959991,365.750000,360.959991,361.940002,5282600,JPM,0.044281
6271,2026-08-18,363.250000,363.570007,359.269989,362.339996,5525100,JPM,0.045905
6272,2026-08-19,357.260010,363.049988,355.649994,363.010010,6696200,JPM,0.211960
6273,2026-08-20,351.549988,357.950012,351.549988,357.600006,6799700,JPM,0.015457
6274,2026-08-21,351.579987,356.859985,350.366608,354.070007,5579895,JPM,-0.179391