import libraries

In [2]:
import yfinance as yf
import pandas as pd
import numpy as np

download data

In [3]:
ticker = ["AAPL", "NVDA", "AMZN", "TSLA", "JPM"]

all_ticker_data = []

for ticker_symbol in ticker:

    ticker_data = yf.download(
        ticker_symbol,
        period="5y"
    )

    ticker_data.columns = ticker_data.columns.get_level_values(0)

    ticker_data = ticker_data.reset_index()

    ticker_data["Ticker"] = ticker_symbol

    all_ticker_data.append(ticker_data)

df = pd.concat(all_ticker_data, ignore_index=True)

df

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Price,Date,Close,High,Low,Open,Volume,Ticker
0,2021-08-23,146.022827,146.491001,144.247644,144.657299,60131800,AAPL
1,2021-08-24,145.935043,147.144509,145.476618,145.769232,48606400,AAPL
2,2021-08-25,144.706055,146.617789,144.159849,146.120340,58991300,AAPL
3,2021-08-26,143.906265,145.447354,143.877005,144.696328,48597200,AAPL
4,2021-08-27,144.940155,145.086455,143.213744,143.847729,55802400,AAPL
...,...,...,...,...,...,...,...
6270,2026-08-17,360.959991,365.750000,360.959991,361.940002,5282600,JPM
6271,2026-08-18,363.250000,363.570007,359.269989,362.339996,5525100,JPM
6272,2026-08-19,357.260010,363.049988,355.649994,363.010010,6696200,JPM
6273,2026-08-20,351.549988,357.950012,351.549988,357.600006,6799700,JPM
6274,2026-08-21,351.579987,356.859985,350.366608,354.070007,5579895,JPM

In [4]:
df.head()

Price,Date,Close,High,Low,Open,Volume,Ticker
0,2021-08-23,146.022827,146.491001,144.247644,144.657299,60131800,AAPL
1,2021-08-24,145.935043,147.144509,145.476618,145.769232,48606400,AAPL
2,2021-08-25,144.706055,146.617789,144.159849,146.120340,58991300,AAPL
3,2021-08-26,143.906265,145.447354,143.877005,144.696328,48597200,AAPL
4,2021-08-27,144.940155,145.086455,143.213744,143.847729,55802400,AAPL

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6275 entries, 0 to 6274
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    6275 non-null   datetime64[ns]
 1   Close   6275 non-null   float64
 2   High    6275 non-null   float64
 3   Low     6275 non-null   float64
 4   Open    6275 non-null   float64
 5   Volume  6275 non-null   int64
 6   Ticker  6275 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 343.3+ KB

In [6]:
df.describe()

Price,Date,Close,High,Low,Open,Volume
count,6275,6275.000000,6275.000000,6275.000000,6275.000000,6.275000e+03
mean,2024-02-20 03:29:58.565737216,188.551326,191.283689,185.696300,188.522896,1.190711e+08
min,2021-08-23 00:00:00,11.199244,11.705988,10.786268,10.943877,3.220500e+06
25%,2022-11-17 00:00:00,132.653481,134.301490,130.864196,132.750000,3.517235e+07
50%,2024-02-21 00:00:00,181.050003,183.595472,178.701850,181.309998,6.163880e+07
75%,2025-05-22 00:00:00,238.897148,243.049399,235.460761,239.238450,1.225152e+08
max,2026-08-21 00:00:00,489.880005,498.829987,485.329987,489.880005,1.543911e+09
std,NaN,91.686067,93.335844,90.035099,91.732489,1.564828e+08

In [7]:
df.shape

(6275, 7)

In [8]:
df.columns

Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker'], dtype='object', name='Price')

Question 1 — Overall performance

In [ ]:
return_caculate =

KeyError: 'Close'